In [63]:
import pandas as pd

import numpy as np

df  = pd.read_csv('mushrooms.csv')
df_original = pd.read_csv('mushrooms.csv')

In [64]:
df_original = pd.read_csv('mushrooms.csv')

In [65]:
df = pd.get_dummies(df)

In [66]:
df = df.drop(['class_e'], axis=1)

In [67]:
df

,class_p,cap-shape_b,cap-shape_c,cap-shape_f,cap-shape_k,cap-shape_s,cap-shape_x,cap-surface_f,cap-surface_g,cap-surface_s,...,population_s,population_v,population_y,habitat_d,habitat_g,habitat_l,habitat_m,habitat_p,habitat_u,habitat_w
0,1,0,0,0,0,0,1,0,0,1,...,1,0,0,0,0,0,0,0,1,0
1,0,0,0,0,0,0,1,0,0,1,...,0,0,0,0,1,0,0,0,0,0
2,0,1,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,1,0,0,0
3,1,0,0,0,0,0,1,0,0,0,...,1,0,0,0,0,0,0,0,1,0
4,0,0,0,0,0,0,1,0,0,1,...,0,0,0,0,1,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8119,0,0,0,0,1,0,0,0,0,1,...,0,0,0,0,0,1,0,0,0,0
8120,0,0,0,0,0,0,1,0,0,1,...,0,1,0,0,0,1,0,0,0,0
8121,0,0,0,1,0,0,0,0,0,1,...,0,0,0,0,0,1,0,0,0,0
8122,1,0,0,0,1,0,0,0,0,0,...,0,1,0,0,0,1,0,0,0,0
8123,0,0,0,0,0,0,1,0,0,1,...,0,0,0,0,0,1,0,0,0,0

In [68]:
# print(df.iloc[8000][1:])
# taking one test data 
input_test = np.array(df.iloc[8000][1:])

In [69]:
input_test

array([1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0], dtype=uint8)

In [70]:
output_test = np.array(df.iloc[8000,1])
print(output_test)

1

In [71]:
df.drop([8000],inplace=True)

In [72]:
print(len(df))
df.head()

8123

,class_p,cap-shape_b,cap-shape_c,cap-shape_f,cap-shape_k,cap-shape_s,cap-shape_x,cap-surface_f,cap-surface_g,cap-surface_s,...,population_s,population_v,population_y,habitat_d,habitat_g,habitat_l,habitat_m,habitat_p,habitat_u,habitat_w
0,1,0,0,0,0,0,1,0,0,1,...,1,0,0,0,0,0,0,0,1,0
1,0,0,0,0,0,0,1,0,0,1,...,0,0,0,0,1,0,0,0,0,0
2,0,1,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,1,0,0,0
3,1,0,0,0,0,0,1,0,0,0,...,1,0,0,0,0,0,0,0,1,0
4,0,0,0,0,0,0,1,0,0,1,...,0,0,0,0,1,0,0,0,0,0

In [73]:
df_arr = []
for i in range(50):
    df_arr.append(df.sample(n = len(df), replace = True))

In [275]:
# df_test.drop(columns = ['class'],inplace = True)

In [11]:
# df.sample(n = 6, replace = True)

In [74]:
len(df_arr)

50

In [77]:
X_train = [0 for i in range(50)]
X_test =[0 for i in range(50)]
y_train= [0 for i in range(50)]
y_test = [0 for i in range(50)]

In [78]:
from sklearn.model_selection import train_test_split
for i in range(50):
    X_train[i], X_test[i], y_train[i], y_test[i] = train_test_split(df_arr[i].iloc[:,1:], df_arr[i].iloc[:,0], test_size=0.2, random_state=2)

In [79]:
X_train[0].head()

,cap-shape_b,cap-shape_c,cap-shape_f,cap-shape_k,cap-shape_s,cap-shape_x,cap-surface_f,cap-surface_g,cap-surface_s,cap-surface_y,...,population_s,population_v,population_y,habitat_d,habitat_g,habitat_l,habitat_m,habitat_p,habitat_u,habitat_w
3051,0,0,1,0,0,0,0,0,0,1,...,0,1,0,1,0,0,0,0,0,0
7276,0,0,0,1,0,0,0,0,1,0,...,1,0,0,0,1,0,0,0,0,0
403,1,0,0,0,0,0,0,0,1,0,...,1,0,0,0,0,0,1,0,0,0
7295,0,0,0,1,0,0,0,0,0,1,...,0,0,0,0,0,1,0,0,0,0
6630,0,0,0,0,0,1,0,0,1,0,...,0,1,0,0,0,1,0,0,0,0

In [80]:
y_train[0].head()

3051    0
7276    0
403     0
7295    1
6630    1
Name: class_p, dtype: uint8

In [82]:
from sklearn.tree import DecisionTreeClassifier

In [83]:
clf = DecisionTreeClassifier( random_state = 42)

In [85]:
clfications = []
for i in range(50):
    clfications.append(clf.fit(X_train[i], y_train[i]))

In [91]:
len(input_test)

117

In [94]:
for i in range(50):
    print(clfications[i].predict(input_test.reshape(1, 117)))

[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]